### ISSUE TITLE
[Enhancement] Unwritten public or protected field[HeartbeatRequestBody]

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#3903]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://github.com/apache/eventmesh/assets/91315508/31e58a14-ecb8-4d7c-98c0-100df6346d56)
![image](https://github.com/apache/eventmesh/assets/91315508/bfc7333a-ac78-4f09-bf3f-e531c9844146)
![image](https://github.com/apache/eventmesh/assets/91315508/4910065f-8a07-45fb-948a-ea0e3c870423)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/client/HeartbeatRequestBody.java line 70-75
analysis and explanation:
No writes were seen to this public/protected field.  All reads of it will return the default value.

### Describe the solution you'd like

![image](https://github.com/apache/eventmesh/assets/91315508/e8ebcc11-6aea-4510-be24-c548f9d86591)
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/consumer/EventMeshHttpConsumer.java line 120,121
![image](https://github.com/apache/eventmesh/assets/91315508/158bfc82-2631-4ce0-b937-17afc880a09b)

eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/HeartBeatProcessor.java line 115,116
![image](https://github.com/apache/eventmesh/assets/91315508/63ee27ec-d1af-4287-b650-488dea4d79c5)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scwlkq** [comment]
![image](https://github.com/apache/eventmesh/assets/89067331/83ddedb7-3b10-43be-9f9a-abade104e268)
@Pil0tXia this issue has be resolved in other issue.

**Comment by Pil0tXia** [comment]
@scwlkq It seems you've mistaken the object class. This issue is still valid.

![image](https://github.com/apache/eventmesh/assets/41445332/13bc5bb1-9ab7-4cb2-a18a-1c992cb97c45)
